# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CosmicSelection',
                'doc_host': 'https://2catycm.github.io',
                'git_url': 'https://github.com/2catycm/CosmicSelection',
                'lib_path': 'CosmicSelection'},
  'syms': {'CosmicSelection.core': {'CosmicSelection.core.foo': ('core.html#foo', 'CosmicSelection/core.py')}}}
